server: 
  port: 8085

spring: 
  profiles:
    include:
      - aws
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/backend?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: ENC(YU+8WnrHcakg8/UZjrU3vw==)
    password: ENC(ERyuianQZWGTkUF0p7Txig==)
  jpa: 
    database: mysql
    generate-ddl: true
    show-sql: true
  thymeleaf: 
    cache: false
    mode: HTML
    prefix: classpath:/
    suffix: .html
    view-names: thymeleaf/*

jwt: 
  secret: jwtsecret

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

propkey: kdkdongki1997

logging: 
  config: classpath:logback-local.xml
