server: 
  port: 8085

spring: 
  datasource: 
    url: jdbc:log4jdbc:mysql://localhost:3306/jpatest?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: root
  jpa: 
    database: mysql
    generate-ddl: true
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:8086
        instance:
          metadata:
            user:
              name: kdkuser
              password: kdk
        username: kdk
        password: kdk123

management:
    endpoints:
        web:
            exposure:
                include: "*"

logging: 
  config: classpath:logback-local.xml
