server: 
  port: 8085

spring: 
  datasource: 
    url: jdbc:log4jdbc:mysql://localhost:3306/jpatest?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: root
  jpa: 
    database: mysql
    generate-ddl: true
    show-sql: true

logging: 
  config: classpath:logback-local.xml